/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cuevadeana;

import Classes.User;
import Templates.DebugWindow;
import Templates.List_movies;
import Templates.Login;
import Templates.Options;
import Templates.RegisterShowtimes;
import Templates.RegisterUser;
import Templates.RegisterMovies;
import Templates.Resolution;
import Templates.SellSeats;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.bson.Document;

/**
 *
 * @author Jose
 */
public class Main extends javax.swing.JFrame implements Resolution {

    /**
     * Creates new form Main
     */
    //===============Variables globales===================
    private User userData = new User();
    //Base de datos por defecto
    private final String URIMONGO = "mongodb://localhost:27017";
    private final String DBNAME = "cine";
    private Mongo mongoDB = null;
    //====================================================

    public Main() {
        initComponents();
        enableButtons(false);//Deshabilitar botones
        visibleButtons(false);
        SC_Login();
    }

    /**
     * Establecer la URI y nombre de la base de datos
     *
     * @param URI URI de mongoDB
     * @param Name Nombre de la base de datos
     */
    public void setDatabase(String URI, String Name) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        MasterPanel = new javax.swing.JPanel();
        Button3 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        UserNameTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        Button1.setBackground(new java.awt.Color(255, 153, 153));
        Button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText(" ");
        Button1.setBorder(null);
        Button1.setBorderPainted(false);
        Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
        });

        Button2.setBackground(new java.awt.Color(255, 153, 153));
        Button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button2.setForeground(new java.awt.Color(255, 255, 255));
        Button2.setText("Lista");
        Button2.setBorder(null);
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2MouseClicked(evt);
            }
        });

        MasterPanel.setBackground(new java.awt.Color(255, 255, 255));
        MasterPanel.setMinimumSize(DEF_RESOLUTION);
        MasterPanel.setPreferredSize(DEF_RESOLUTION);

        javax.swing.GroupLayout MasterPanelLayout = new javax.swing.GroupLayout(MasterPanel);
        MasterPanel.setLayout(MasterPanelLayout);
        MasterPanelLayout.setHorizontalGroup(
            MasterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MasterPanelLayout.setVerticalGroup(
            MasterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Button3.setBackground(new java.awt.Color(255, 153, 153));
        Button3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button3.setForeground(new java.awt.Color(255, 255, 255));
        Button3.setText("Venta");
        Button3.setBorder(null);
        Button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button3MouseClicked(evt);
            }
        });

        Button4.setText("Opciones");
        Button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button4MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("La cueva de ana");

        UserNameTitle.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        UserNameTitle.setForeground(new java.awt.Color(255, 255, 255));
        UserNameTitle.setText("  ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(UserNameTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(MasterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MasterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JPanel actualScenne = null;

    //Re dibuja el JPanel cuando se cambia el tamaño del contenedor 
    public void changeScenne(JPanel scenne) {
        actualScenne = scenne; //910 *630
        MasterPanel.removeAll();
        MasterPanel.add(scenne);
        scenne.setSize(MasterPanel.getWidth(), MasterPanel.getHeight());
        MasterPanel.revalidate();
        MasterPanel.repaint();
    }

    private void SC_RegisterShowtime() {
        RegisterShowtimes re = new RegisterShowtimes(mongoDB);
        changeScenne(re);
    }

    private void SC_SellSeats() {
        SellSeats v = new SellSeats(mongoDB, userData);
        changeScenne(v);
    }

    private void SC_RegisterMovie() {
        RegisterMovies registerMovie = new RegisterMovies(mongoDB);
        changeScenne(registerMovie);
    }
    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
        // TODO add your handling code here:
        if (userData.getRol().equals("Administrador")) {
            SC_RegisterMovie();
        } else {
            SC_SellSeats();
        }
    }//GEN-LAST:event_Button1MouseClicked

    private void SC_ListMovies() {
        List_movies list_movies = new List_movies(mongoDB, this);
        changeScenne(list_movies);
    }

    private void SC_RegisterUser() {
        RegisterUser newUser = new RegisterUser(mongoDB);
        changeScenne(newUser);
    }
    private void Button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseClicked
        // TODO add your handling code here:
        if (userData.getRol().equals("Administrador")) {
            SC_RegisterShowtime();
        } else {
            SC_ListMovies();
        }
    }//GEN-LAST:event_Button2MouseClicked

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        if (actualScenne != null) {
            actualScenne.setSize(MasterPanel.getWidth(), MasterPanel.getHeight());
            MasterPanel.revalidate();
            MasterPanel.repaint();
        }
    }//GEN-LAST:event_formComponentResized

    /**
     * Valida al usuario y estable sus datos en local
     *
     * @param username Nombre del usuario
     * @param pass Contraseña del usuario
     */
    public void login(String username, String pass) {
        //Establecer coneccion con mongoDB
        mongoDB = new Mongo(URIMONGO, DBNAME);
        //Validar usuario

        User user = new User();
        Document userDataLogin = mongoDB.findUser(user.hashPassword(pass), username);
        if (userDataLogin.getString("Password").equals(user.hashPassword(pass))) {
            user.setId(userDataLogin.getObjectId("_id").toString());
            user.setUserName(userDataLogin.getString("UserName"));
            user.setName(userDataLogin.getString("Name"));
            user.setIdentification(userDataLogin.getString("Identification"));
            user.setRol(userDataLogin.getString("Rol"));
            if (user.getRol().equals("Cajero")) {
                user.setCashRegister(userDataLogin.getString("CashRegister"));
            }
            this.userData = user;
            //Cambiar botones segun el cargo
            Button1.setText(user.getRol().equals("Administrador") ? "Registrar" : "Venta");
            Button2.setText(user.getRol().equals("Administrador") ? "Funciones" : "Peliculas");
            Button3.setText(user.getRol().equals("Administrador") ? "Usuarios" : " ");
            Button4.setText("Salir");
            //
            UserNameTitle.setText(user.getName());
            enableButtons(true);
            visibleButtons(true);
            SC_ListMovies();
        } else {
            DebugWindow.Message("warning", "Usuario invalido", "Error de ingreso");
            SC_Login();
        }
    }
    private void Button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button3MouseClicked
        // TODO add your handling code here:
        if (userData.getRol().equals("Administrador")) {
            SC_RegisterUser();
        } else {

        }
    }//GEN-LAST:event_Button3MouseClicked

    private void Button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button4MouseClicked
        // TODO add your handling code here:
        if (Button4.getText().equals("Opciones")) {
            Options op = new Options(this);
            op.setVisible(true);
        } else {
            //Cerrar sesion
            int op = JOptionPane.showConfirmDialog(this, "¿Estas seguro de querer cerrar sesion?", "Cerrar sesion", JOptionPane.OK_CANCEL_OPTION);
            if (op == 0) {
                //Cerrar conexion
                mongoDB.closeConnection();
                //Limpiar datos
                this.userData = new User();
                UserNameTitle.setText("");
                //Repintar login
                SC_Login();
            }
        }
    }//GEN-LAST:event_Button4MouseClicked

    private void SC_Login() {
        Login loginT = new Login(this);
        loginT.setName("Login");
        changeScenne(loginT);
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (mongoDB != null) {
            mongoDB.closeConnection();
        }
    }//GEN-LAST:event_formWindowClosing

    private void enableButtons(boolean enable) {
        Button1.setEnabled(enable);
        Button2.setEnabled(enable);
        Button3.setEnabled(enable);
    }

    private void visibleButtons(boolean isVisible) {
        Button1.setVisible(isVisible);
        Button2.setVisible(isVisible);
        Button3.setVisible(isVisible);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JPanel MasterPanel;
    private javax.swing.JLabel UserNameTitle;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
