/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Templates;

import Classes.Movie;
import com.mycompany.cuevadeana.Mongo;
import java.awt.GridLayout;
import java.util.List;

/**
 *
 * @author Jose
 */
public class List_movies extends javax.swing.JPanel {

    /**
     * Creates new form List_movies
     */
    public List_movies() {
        initComponents();
        viewMovies();
    }

    private void viewMovies() {

        Panel.removeAll();
        Mongo mongoDB = new Mongo();
        List<Movie> mongoMovies = mongoDB.getMovies(0, 5);
        final int maxUn = mongoMovies.size();
        final int columns = 5, rows = (int) Math.ceil((double) maxUn / columns);
        Panel.setLayout(new GridLayout(rows, columns, 10, 10));

        for (Movie movie : mongoMovies) {
            MoviePoster mt = new MoviePoster();
            mt.setData(movie.getTitle(), movie.getDate());
            mt.setPoster(movie.getPoster());
            Panel.add(mt);
        }

        Panel.revalidate();
        Panel.repaint();
        mongoDB.closeConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Comedia = new javax.swing.JCheckBox();
        Accion = new javax.swing.JCheckBox();
        Terror = new javax.swing.JCheckBox();
        Fantasia = new javax.swing.JCheckBox();
        Drama = new javax.swing.JCheckBox();
        Familia = new javax.swing.JCheckBox();
        Suspenso = new javax.swing.JCheckBox();
        Misterio = new javax.swing.JCheckBox();
        Ciencia_f = new javax.swing.JCheckBox();
        Aventura = new javax.swing.JCheckBox();
        Romance = new javax.swing.JCheckBox();
        Crimen = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Classification = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(910, 630));

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setBorder(null);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        Panel1.setViewportView(Panel);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categorias");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Comedia.setBackground(new java.awt.Color(255, 255, 255));
        Comedia.setText("Comedia");
        Comedia.setBorderPainted(true);
        Comedia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Accion.setBackground(new java.awt.Color(255, 255, 255));
        Accion.setText("Acción");
        Accion.setBorderPainted(true);
        Accion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Terror.setBackground(new java.awt.Color(255, 255, 255));
        Terror.setText("Terror");
        Terror.setBorderPainted(true);
        Terror.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Fantasia.setBackground(new java.awt.Color(255, 255, 255));
        Fantasia.setText("Fantasia");
        Fantasia.setBorderPainted(true);
        Fantasia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Drama.setBackground(new java.awt.Color(255, 255, 255));
        Drama.setText("Drama");
        Drama.setBorderPainted(true);
        Drama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Familia.setBackground(new java.awt.Color(255, 255, 255));
        Familia.setText("Familia");
        Familia.setBorderPainted(true);
        Familia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Suspenso.setBackground(new java.awt.Color(255, 255, 255));
        Suspenso.setText("Suspenso");
        Suspenso.setBorderPainted(true);
        Suspenso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Misterio.setBackground(new java.awt.Color(255, 255, 255));
        Misterio.setText("Misterio");
        Misterio.setBorderPainted(true);
        Misterio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Ciencia_f.setBackground(new java.awt.Color(255, 255, 255));
        Ciencia_f.setText("Ciencia ficción");
        Ciencia_f.setBorderPainted(true);
        Ciencia_f.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Aventura.setBackground(new java.awt.Color(255, 255, 255));
        Aventura.setText("Aventura");
        Aventura.setBorderPainted(true);
        Aventura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Romance.setBackground(new java.awt.Color(255, 255, 255));
        Romance.setText("Romance");
        Romance.setBorderPainted(true);
        Romance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Crimen.setBackground(new java.awt.Color(255, 255, 255));
        Crimen.setText("Crimen");
        Crimen.setBorderPainted(true);
        Crimen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accion)
                    .addComponent(Terror)
                    .addComponent(Fantasia)
                    .addComponent(Comedia)
                    .addComponent(Familia)
                    .addComponent(Drama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Romance)
                    .addComponent(Crimen)
                    .addComponent(Suspenso)
                    .addComponent(Aventura)
                    .addComponent(Ciencia_f)
                    .addComponent(Misterio))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Suspenso)
                        .addGap(18, 18, 18)
                        .addComponent(Misterio)
                        .addGap(18, 18, 18)
                        .addComponent(Ciencia_f)
                        .addGap(18, 18, 18)
                        .addComponent(Aventura)
                        .addGap(18, 18, 18)
                        .addComponent(Romance)
                        .addGap(18, 18, 18)
                        .addComponent(Crimen))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Comedia)
                        .addGap(18, 18, 18)
                        .addComponent(Accion)
                        .addGap(18, 18, 18)
                        .addComponent(Terror)
                        .addGap(18, 18, 18)
                        .addComponent(Fantasia)
                        .addGap(18, 18, 18)
                        .addComponent(Drama)
                        .addGap(18, 18, 18)
                        .addComponent(Familia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre:");

        jTextField1.setText("jTextField1");

        jLabel3.setText("Actores");

        jTextField2.setText("jTextField2");

        jLabel4.setText("Director");

        jTextField3.setText("jTextField3");

        jButton1.setText("Buscar");

        Classification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "T", "7", "12", "15", "18", "X", "Prohibido" }));

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setText("Clasificación");

        jLabel6.setText("Duracion");

        jTextField4.setText("jTextField4");

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setText("Fecha");

        DateChooser.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Classification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Classification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Accion;
    private javax.swing.JCheckBox Aventura;
    private javax.swing.JCheckBox Ciencia_f;
    private javax.swing.JComboBox<String> Classification;
    private javax.swing.JCheckBox Comedia;
    private javax.swing.JCheckBox Crimen;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JCheckBox Drama;
    private javax.swing.JCheckBox Familia;
    private javax.swing.JCheckBox Fantasia;
    private javax.swing.JCheckBox Misterio;
    private javax.swing.JPanel Panel;
    private javax.swing.JScrollPane Panel1;
    private javax.swing.JCheckBox Romance;
    private javax.swing.JCheckBox Suspenso;
    private javax.swing.JCheckBox Terror;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
