/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Templates;

import Classes.Movie;
import Classes.Showtime;
import Classes.Theater;
import Classes.Window;
import com.mycompany.cuevadeana.Mongo;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose
 */
public class RegisterShowtimes extends javax.swing.JPanel implements Resolution {

    private Mongo mongoDB;
    private Theater theater = new Theater();
    private List<Movie> movies;
    private final int delayTime = 20; // Tiempo entre funciones
    private final int openTime = 7; // Hora de apertura
    Window window = new Window();

    /**
     * Crea un nuevo formulario RegisterShowtimes.
     *
     * @param client El cliente de MongoDB.
     */
    public RegisterShowtimes(Mongo client) {
        initComponents();
        mongoDB = client;
        getMovieTitles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListMovies = new javax.swing.JComboBox<>();
        TheaterFeatures = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        DateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setMinimumSize(DEF_RESOLUTION);
        setPreferredSize(new java.awt.Dimension(1336, 768));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pelicula", "Inicio", "Fin", "Duración (Minutos)"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 19)); // NOI18N
        jLabel5.setText("Listado de las peliculas agregadas al horario");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel6.setText("*Los horarios tienen adicionado el tiempo entre proyecciones de 20 minutos y el horario es de 7 A.M. a 11 P.M.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(204, 204, 204))
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de función de  peliculas");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pelicula");

        ListMovies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        ListMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListMoviesActionPerformed(evt);
            }
        });

        TheaterFeatures.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Sala 1    - 2D", "Sala 2    - 2D - CC", "Sala 3    - 2D ", "Sala 4    - 3D", "Sala 5    - 3D - CC", "Sala 6    - 3D", "Sala 7    - 4D - CC", "Sala 8    - 4D", "Sala 9    - 4D", " " }));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sala");

        AddButton.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 102, 102));
        AddButton.setText("Añadir película");
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha");

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Registrar función");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Guarda la funcion en el servidor, con el boton de abajo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(31, 31, 31)
                                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(33, 33, 33)
                                    .addComponent(TheaterFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ListMovies, 0, 360, Short.MAX_VALUE)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TheaterFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getMovieTitles() {
        movies = mongoDB.getMovies(0, 0);
        if (movies.isEmpty()) {
            ListMovies.removeItemAt(0);
            ListMovies.addItem("No hay peliculas disponibles");
            ListMovies.setSelectedIndex(0);
        } else {
            for (Movie movie : movies) {
                ListMovies.addItem(movie.getTitle());
            }
        }
    }

    private void updateTable() {
        DefaultTableModel modelo = (DefaultTableModel) Table.getModel();
        modelo.setRowCount(0);
        for (Showtime showtime : theater.getShowtimes()) {
            Object[] row = {showtime.getMovie(), showtime.getStartHour(), showtime.getEndHour(), showtime.getDuration()};
            modelo.addRow(row);
        }
    }

    private void registerShow() {
        Date date = DateChooser.getDate();
        if (date != null) {
            if (theater.getDate() == null) {
                //Bloquear DateChooser
                DateChooser.setEnabled(false);
                //Ingreasar fecha
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String dateString = sdf.format(date);
                theater.setDate(dateString);
                /*
            Sala 1    - 2D
            Sala 2    - 2D - CC
            Sala 3    - 2D 
            Sala 4    - 3D
            Sala 5    - 3D - CC
            Sala 6    - 3D
            Sala 7    - 4D - CC
            Sala 8    - 4D
            Sala 9    - 4D
                 */
                //Bloquear selecto de sala
                TheaterFeatures.setEnabled(false);
                //Establecer caracteristicas
                String features = "";
                int temp = TheaterFeatures.getSelectedIndex();
                if (temp >= 1 && temp <= 3) {
                    features += "2D";
                } else if (temp >= 2 && temp <= 6) {
                    features += "3D";
                } else if (temp >= 7 && temp <= 9) {
                    features += "4D";
                }
                if (temp == 2 || temp == 5 || temp == 7) {
                    features += ", CC";
                }
                theater.setFeatures(features);
                //Obtener nombre de la sala
                String[] salas = TheaterFeatures.getSelectedItem().toString().split(" ");
                theater.setName(salas[0] + " " + salas[1]);

            }
            //Validar que haya una pelicula seleccionada
            if (ListMovies.getSelectedIndex() != 0) {
                Showtime showtime = new Showtime();
                int index = -1;
                for (int i = 0; i < movies.size(); i++) {
                    if (movies.get(i).getTitle().equals(ListMovies.getSelectedItem().toString())) {
                        index = i;
                        break;
                    }
                }
                if (index != -1) {
                    Movie movie = movies.get(index);
                    showtime.setMovie(movie);
                    //Calculo de horas
                    LocalTime startTime;
                    LocalTime endTime;
                    //Calcula la hora de la primer funcion
                    if (theater.getShowtimes().isEmpty()) {
                        //Inicia las proyecciones , segun openTime
                        startTime = LocalTime.of(openTime, 0);
                        endTime = startTime.plusMinutes(movie.getDuration());
                    } else {
                        //Obtener ultima funcion
                        startTime = theater.getShowtimes().getLast().getEndHour();
                        //Tiempo entre funcion
                        startTime = startTime.plusMinutes(delayTime);
                        endTime = startTime.plusMinutes(movie.getDuration());
                    }
                    //Comprar si la pelicula no pasa de las 11 PM
                    int end = endTime.getHour(), start = startTime.getHour();
                    if ((start >= 0 && start < openTime || start >= 23) || (end >= 0 && end < openTime || end >= 23)) {
                        Window.Message("warning", "Ya no se pueden agregar mas peliculas porque se supera el limite de horario", "Limite de horario");
                    } else {
                        showtime.setStartHour(startTime);
                        showtime.setEndHour(endTime);
                        //añadir showtime en Theater
                        theater.addShowtime(showtime);
                        //Deseleccionar pelicula
                        ListMovies.setSelectedIndex(0);
                        //Actualizar tabla
                        updateTable();
                        Window.Message("info", "Pelicula añadida", "Pelicula registrada en la funcion");
                    }
                }

            } else {
                Window.Message("warning", "Pelicula no seleccionada", "Pelicula no seleccionada");
            }
        } else {
            Window.Message("warning", "Fecha no seleccionada", "Fecha no seleccionada");
        }

    }

    private void enableInputs() {
        TheaterFeatures.setSelectedIndex(0);
        TheaterFeatures.setEnabled(true);
        DateChooser.setDate(null);
        DateChooser.setEnabled(true);
    }

    //Guardar en la base de datos
    private void saveShowtime() {
        if (!theater.getShowtimes().isEmpty()) {
            try {
                //Validar si ya existe un registro del mismo dia
                System.out.println("Date: " + theater.getDate());
                if (mongoDB.findTheater(theater.getName(), theater.getDate()) == null) {
                    mongoDB.insert(theater);
                    //mongoDB.closeConnection();
                    //Limpiar datos
                    theater = new Theater();
                    enableInputs();
                    updateTable();
                } else {
                    Window.Message("danger", "Fecha ya registrada", "Error en registrar funcion");
                    enableInputs();
                }

            } catch (Exception ex) {
                Window.Message("danger", ex.toString(), "Error en registrar funcion");
            }
        }
    }
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        // TODO add your handling code here:
        registerShow();
    }//GEN-LAST:event_AddButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        saveShowtime();
    }//GEN-LAST:event_jButton1MouseClicked

    private void ListMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListMoviesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListMoviesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JComboBox<String> ListMovies;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> TheaterFeatures;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
