/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Templates;

import Classes.Movie;
import Classes.Showtime;
import Classes.Theater;
import com.mycompany.cuevadeana.Mongo;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose
 */
public class RegisterShowtimes extends javax.swing.JPanel {

    private Mongo mongoDB;
    private Theater theater = new Theater();
    private List<Movie> movies;
    private final int delayTime = 20;//Tiempo entre funciones
    private final int openTime = 7; //Hora de apertura
    DebugWindow window = new DebugWindow();

    /**
     * Creates new form RegisterShowtimes
     */
    public RegisterShowtimes(Mongo client) {
        initComponents();
        mongoDB = client;
        getMovieTitles();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ListMovies = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TheaterFeatures = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jLabel1.setText("Registro de funcion de las peliculas");

        ListMovies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jLabel2.setText("Pelicula");

        jLabel3.setText("Sala");

        TheaterFeatures.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Sala 1    - 2D", "Sala 2    - 2D - CC", "Sala 3    - 2D ", "Sala 4    - 3D", "Sala 5    - 3D - CC", "Sala 6    - 3D", "Sala 7    - 4D - CC", "Sala 8    - 4D", "Sala 9    - 4D", " " }));

        jLabel4.setText("Fecha");

        AddButton.setText("Añadir");
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pelicula", "Inicio", "Fin", "Duración"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jButton1.setText("Registrar dia");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TheaterFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(DateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ListMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(AddButton))
                                .addGap(60, 60, 60))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(ListMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(TheaterFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4))
                            .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(AddButton)
                        .addGap(80, 80, 80)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getMovieTitles() {
        movies = mongoDB.getMovies(0, 0);
        if (movies.isEmpty()) {
            ListMovies.removeItemAt(0);
            ListMovies.addItem("No hay peliculas disponibles");
            ListMovies.setSelectedIndex(0);
        } else {
            for (Movie movie : movies) {
                ListMovies.addItem(movie.getTitle());
            }
        }
    }

    private void updateTable() {
        DefaultTableModel modelo = (DefaultTableModel) Table.getModel();
        modelo.setRowCount(0);
        for (Showtime showtime : theater.getShowtimes()) {
            Object[] row = {showtime.getMovie(), showtime.getStartHour(), showtime.getEndHour(), showtime.getDuration()};
            modelo.addRow(row);
        }
    }

    private void registerShow() {
        Date date = DateChooser.getDate();
        if (date != null) {
            if (theater.getDate() == null) {
                //Bloquear DateChooser
                DateChooser.setEnabled(false);
                //Ingreasar fecha
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String dateString = sdf.format(date);
                theater.setDate(dateString);
                /*
            Sala 1    - 2D
            Sala 2    - 2D - CC
            Sala 3    - 2D 
            Sala 4    - 3D
            Sala 5    - 3D - CC
            Sala 6    - 3D
            Sala 7    - 4D - CC
            Sala 8    - 4D
            Sala 9    - 4D
                 */
                //Bloquear selecto de sala
                TheaterFeatures.setEnabled(false);
                //Establecer caracteristicas
                String features = "";
                int temp = TheaterFeatures.getSelectedIndex();
                if (temp >= 1 && temp <= 3) {
                    features += "2D";
                } else if (temp >= 2 && temp <= 6) {
                    features += "3D";
                } else if (temp >= 7 && temp <= 9) {
                    features += "4D";
                }
                if (temp == 2 || temp == 5 || temp == 7) {
                    features += ", CC";
                }
                theater.setFeatures(features);
                //Obtener nombre de la sala
                String[] salas = TheaterFeatures.getSelectedItem().toString().split(" ");
                theater.setName(salas[0] + " " + salas[1]);

            }
            //Validar que haya una pelicula seleccionada
            if (ListMovies.getSelectedIndex() != 0) {
                Showtime showtime = new Showtime();
                int index = -1;
                for (int i = 0; i < movies.size(); i++) {
                    if (movies.get(i).getTitle().equals(ListMovies.getSelectedItem().toString())) {
                        index = i;
                        break;
                    }
                }
                if (index != -1) {
                    Movie movie = movies.get(index);
                    showtime.setMovie(movie);
                    //Calculo de horas
                    LocalTime startTime;
                    LocalTime endTime;
                    //Calcula la hora de la primer funcion
                    if (theater.getShowtimes().isEmpty()) {
                        //Inicia las proyecciones , segun openTime
                        startTime = LocalTime.of(openTime, 0);
                        endTime = startTime.plusMinutes(movie.getDuration());
                    } else {
                        //Obtener ultima funcion
                        startTime = theater.getShowtimes().getLast().getEndHour();
                        //Tiempo entre funcion
                        startTime = startTime.plusMinutes(delayTime);
                        endTime = startTime.plusMinutes(movie.getDuration());
                    }
                    //Comprar si la pelicula no pasa de las 11 PM
                    int end = endTime.getHour(), start = startTime.getHour();
                    if ((start >= 0 && start < openTime || start >= 23) || (end >= 0 && end < openTime || end >= 23)) {
                        window.newWindow("warning", "Ya no se pueden agregar mas peliculas", "Limite de horario");
                    } else {
                        showtime.setStartHour(startTime);
                        showtime.setEndHour(endTime);
                        //añadir showtime en Theater
                        theater.addShowtime(showtime);
                        //Deseleccionar pelicula
                        ListMovies.setSelectedIndex(0);
                        //Actualizar tabla
                        updateTable();
                        window.newWindow("info", "Pelicula añadida", "Pelicula registrada en la funcion");
                    }
                }

            } else {
                window.newWindow("warning", "Pelicula no seleccionada", "Pelicula no seleccionada");
            }
        } else {
            window.newWindow("warning", "Fecha no seleccionada", "Fecha no seleccionada");
        }

    }

    private void enableInputs() {
        TheaterFeatures.setSelectedIndex(0);
        TheaterFeatures.setEnabled(true);
        DateChooser.setDate(null);
        DateChooser.setEnabled(true);
    }

    private void saveShowtime() {
        if (!theater.getShowtimes().isEmpty()) {
            try {
                Mongo mongoDB = new Mongo();
                //Validar si ya existe un registro del mismo dia
                System.out.println("Date: " + theater.getDate());
                if (mongoDB.findTheater(theater.getName(), theater.getDate()) == null) {
                    mongoDB.insert(theater);
                    mongoDB.closeConnection();
                    //Limpiar datos
                    theater = new Theater();
                    enableInputs();
                    updateTable();
                } else {
                    window.newWindow("danger", "Fecha ya registrada", "Error en registrar funcion");
                    enableInputs();
                }

            } catch (Exception ex) {
                window.newWindow("danger", ex.toString(), "Error en registrar funcion");
            }
        }
    }
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        // TODO add your handling code here:
        registerShow();
    }//GEN-LAST:event_AddButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        saveShowtime();
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JComboBox<String> ListMovies;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> TheaterFeatures;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
